import type {
  AdminActivity,
  AdminSession,
  AdminToken,
} from "../_actions/audit";

const seedTime = Date.UTC(2025, 0, 15);
const day = 86_400_000;

export const mockSessions: AdminSession[] = [
  {
    id: "sess_001",
    userId: "user_001",
    userEmail: "john@acme.com",
    ipAddress: "192.168.1.10",
    userAgent: "Mozilla/5.0 (Macintosh)",
    activeOrganizationId: "org_001",
    activeTeamId: null,
    impersonatedBy: null,
    createdAt: seedTime,
    expiresAt: seedTime + 7 * day,
  },
  {
    id: "sess_002",
    userId: "user_002",
    userEmail: "jane@beta.com",
    ipAddress: "10.0.0.5",
    userAgent: "Mozilla/5.0 (Windows)",
    activeOrganizationId: null,
    activeTeamId: null,
    impersonatedBy: null,
    createdAt: seedTime - 2 * day,
    expiresAt: seedTime + 5 * day,
  },
  {
    id: "sess_003",
    userId: "user_003",
    userEmail: "bob@corp.com",
    ipAddress: "172.16.0.3",
    userAgent: "Mozilla/5.0 (Linux)",
    activeOrganizationId: null,
    activeTeamId: null,
    impersonatedBy: "user_001",
    createdAt: seedTime - 30 * day,
    expiresAt: seedTime - day,
  },
];

export const mockTokens: AdminToken[] = [
  {
    id: "at_001",
    tokenPrefix: "a1b2c3d4…",
    type: "access",
    clientId: "cli_contentapi_a1b2c3d4e5f6",
    clientName: "Content API",
    userId: "user_001",
    userEmail: "john@acme.com",
    scopes: ["content:read"],
    expiresAt: seedTime + 900_000,
    createdAt: seedTime,
  },
  {
    id: "at_002",
    tokenPrefix: "e5f6g7h8…",
    type: "access",
    clientId: "cli_portal_5t4s3r2q1p0o",
    clientName: "Vendor Portal",
    userId: "user_002",
    userEmail: "jane@beta.com",
    scopes: ["vendor:read"],
    expiresAt: seedTime + 900_000,
    createdAt: seedTime - day,
  },
];

export const mockRefreshTokens: AdminToken[] = [
  {
    id: "rt_001",
    tokenPrefix: "r1r2r3r4…",
    type: "refresh",
    clientId: "cli_portal_5t4s3r2q1p0o",
    clientName: "Vendor Portal",
    userId: "user_002",
    userEmail: "jane@beta.com",
    scopes: ["vendor:read"],
    expiresAt: seedTime + 30 * day,
    createdAt: seedTime - day,
  },
];

export const mockActivities: AdminActivity[] = [
  {
    id: "act_001",
    actorId: "user_001",
    actorType: "user",
    actorEmail: "admin@example.test",
    action: "user.update",
    targetType: "user",
    targetId: "user_001",
    scope: "platform",
    organizationId: null,
    actorPlatformRole: "admin",
    actorOrganizationRole: null,
    steppedUp: false,
    summary: "Updated user user_001: name",
    details: {
      path: "/admin/update-user",
      userId: "user_001",
      changedFields: ["name"],
    },
    before: { name: "John" },
    after: { name: "John Doe" },
    metadata: { path: "/admin/update-user" },
    createdAt: seedTime,
  },
  {
    id: "act_002",
    actorId: "user_001",
    actorType: "user",
    actorEmail: "admin@example.test",
    action: "organization.update",
    targetType: "organization",
    targetId: "org_001",
    scope: "organization",
    organizationId: "org_001",
    actorPlatformRole: "admin",
    actorOrganizationRole: "owner",
    steppedUp: false,
    summary: "Updated organization org_001: name, slug",
    details: {
      path: "/organization/update",
      organizationId: "org_001",
      changedFields: ["name", "slug"],
    },
    before: { name: "Acme", slug: "acme-old" },
    after: { name: "Acme Corp", slug: "acme" },
    metadata: { path: "/organization/update" },
    createdAt: seedTime - 12 * 60 * 60 * 1000,
  },
  {
    id: "act_003",
    actorId: "user_001",
    actorType: "user",
    actorEmail: "admin@example.test",
    action: "team.add_member",
    targetType: "team",
    targetId: "team_001",
    scope: "organization",
    organizationId: "org_001",
    actorPlatformRole: "admin",
    actorOrganizationRole: "owner",
    steppedUp: false,
    summary: "Added user user_003 to team team_001",
    details: {
      path: "/organization/add-team-member",
      teamId: "team_001",
      userId: "user_003",
      organizationId: "org_001",
    },
    before: null,
    after: { userId: "user_003" },
    metadata: { path: "/organization/add-team-member" },
    createdAt: seedTime - day,
  },
];
