import type {
  RegistrationIntent,
  RegistrationPolicy,
} from "../_actions/registration-policies";

const now = Date.now();

function quota(
  policyId: string,
  quotaLimit: number | null,
  quotaUsed: number,
  quotaReserved: number,
  quotaTarget = "memberships",
) {
  return {
    policyId,
    quotaLimit,
    quotaUsed,
    quotaReserved,
    quotaTarget,
  };
}

export const mockRegistrationPolicies: RegistrationPolicy[] = [
  {
    id: "regpol_content_beta",
    slug: "content-beta",
    name: "Content beta",
    status: "enabled",
    mode: "client_initiated",
    clientId: "cli_content_web",
    organizationId: "org_001",
    resourceServerId: "rs_content",
    allowedScopes: ["openid", "profile", "email", "content:read"],
    emailDomains: ["acme.com"],
    defaultRole: "member",
    defaultTeamIds: [],
    quotaLimit: 1000,
    quotaTarget: "memberships",
    requiresEmailVerification: true,
    startsAt: now - 86_400_000,
    expiresAt: now + 2_592_000_000,
    createdAt: now - 172_800_000,
    updatedAt: now - 3_600_000,
    quota: quota("regpol_content_beta", 1000, 231, 4),
  },
  {
    id: "regpol_acme_invites",
    slug: "acme-invites",
    name: "Acme invites",
    status: "paused",
    mode: "invite_only",
    clientId: null,
    organizationId: "org_001",
    resourceServerId: null,
    allowedScopes: [],
    emailDomains: ["acme.com"],
    defaultRole: "member",
    defaultTeamIds: ["team_readers"],
    quotaLimit: 50,
    quotaTarget: "memberships",
    requiresEmailVerification: true,
    startsAt: null,
    expiresAt: null,
    createdAt: now - 604_800_000,
    updatedAt: now - 7_200_000,
    quota: quota("regpol_acme_invites", 50, 4, 0),
  },
  {
    id: "regpol_trial",
    slug: "trial",
    name: "Trial waitlist",
    status: "draft",
    mode: "public_limited",
    clientId: null,
    organizationId: null,
    resourceServerId: null,
    allowedScopes: ["openid", "profile", "email"],
    emailDomains: [],
    defaultRole: "member",
    defaultTeamIds: [],
    quotaLimit: null,
    quotaTarget: "accounts",
    requiresEmailVerification: true,
    startsAt: null,
    expiresAt: null,
    createdAt: now - 1_209_600_000,
    updatedAt: now - 86_400_000,
    quota: quota("regpol_trial", null, 0, 0, "accounts"),
  },
];

export const mockRegistrationIntents: RegistrationIntent[] = [
  {
    id: "regint_completed",
    policyId: "regpol_content_beta",
    clientId: "cli_content_web",
    organizationId: "org_001",
    invitationId: null,
    requestedScopes: ["openid", "profile", "email", "content:write"],
    allowedScopes: ["openid", "profile", "email", "content:read"],
    resource: "https://content.example.test",
    email: "new@acme.com",
    status: "completed",
    expiresAt: now + 900_000,
    createdAt: now - 600_000,
    updatedAt: now - 420_000,
    completedAt: now - 420_000,
    userId: "user_new",
    failureReason: null,
  },
  {
    id: "regint_continue_failed",
    policyId: "regpol_content_beta",
    clientId: "cli_content_web",
    organizationId: "org_001",
    invitationId: null,
    requestedScopes: ["openid", "profile", "email"],
    allowedScopes: ["openid", "profile", "email"],
    resource: null,
    email: "retry@acme.com",
    status: "continuation_failed",
    expiresAt: now + 900_000,
    createdAt: now - 300_000,
    updatedAt: now - 120_000,
    completedAt: now - 180_000,
    userId: "user_retry",
    failureReason: "oauth_continuation_failed",
  },
];
